const STATUS_LABELS = Object.freeze({
  ABSTAIN: '暂不判断',
  ACTIVE: '运行中',
  ADD: '加仓',
  AFTER_CLOSE: '收盘后',
  AVAILABLE: '可用',
  AVOID: '建议回避',
  BALANCED: '均衡震荡',
  BEAR: '弱势',
  BEFORE_OPEN: '开盘前',
  BUILD_DAILY_INSIGHT: '汇总日报结论',
  BUILD_RESEARCH_DAILY_REPORT: '生成投研日报',
  BUILD_SAMPLES: '固化研究样本',
  BULL: '强势',
  BUY: '买入',
  CANDIDATE: '候选模型',
  CHALLENGER: '候选策略',
  CHALLENGER_SHADOW: '候选策略影子运行',
  CHAMPION: '正式策略',
  CHECK_DATA_QUALITY: '检查数据质量',
  CLOSE: '收盘样本',
  COMPLETED: '已完成',
  COMPUTE_FACTORS: '计算因子',
  CRITICAL: '严重告警',
  CURRENT: '当前版本',
  CURRENT_CLOSE: '当日收盘数据',
  DATA_UNAVAILABLE: '数据不可用',
  DECISION: '决策',
  DEFENSIVE: '防御模式',
  DISABLED: '已停用',
  DOWN: '看跌',
  DRAFT: '草稿',
  EMPTY: '暂无数据',
  EMPTY_RESULT: '暂无结果',
  ENABLED: '已启用',
  EVALUATED: '已评估',
  EVALUATE_PREDICTIONS: '评估成熟预测',
  EXECUTED: '已成交',
  EXCLUDED: '已排除',
  FAILED: '执行失败',
  FAILED_PIPELINE: '流水线失败',
  FETCH_DATA: '抓取收盘数据',
  FETCH_SOURCE_DATA: '采集研究数据',
  FINALIZED: '已冻结',
  FRESH: '数据新鲜',
  FROZEN: '已冻结',
  FUNDAMENTAL: '基本面',
  GENERATE_PREDICTIONS: '生成预测结果',
  GENERATE_REPORTS: '生成个股报告',
  GLOBAL_DAILY_RESEARCH: '全局日度研究',
  HEALTHY: '健康',
  HISTORICAL_BOOTSTRAP: '历史冷启动',
  HIGH: '高风险',
  HIGH_RISK: '高风险',
  HOLD: '持有',
  HUMAN: '人工操作',
  HUMAN_CHALLENGER_REJECTED: '人工拒绝候选策略',
  HUMAN_PROMOTION_CONFIRMED: '人工确认策略晋级',
  HUMAN_ROLLBACK_CONFIRMED: '人工确认策略回滚',
  IDLE: '等待中',
  INACTIVE: '未启用',
  INSUFFICIENT_DATA: '数据积累不足',
  INTRADAY: '盘中',
  LABEL_VERIFICATION: '成熟标签验证',
  LOW: '低风险',
  LOW_SAMPLE: '样本不足',
  MARKET: '市场',
  MATURED: '标签已成熟',
  MATURE_SAMPLE_LABELS: '生成成熟标签',
  MEDIUM: '中风险',
  MISSING: '数据缺失',
  MODEL: '模型推理',
  MODEL_TRAINING: '模型训练',
  NEGATIVE: '负向',
  NEUTRAL: '中性',
  NO_TRIGGER: '未触发',
  PARTIAL_READY: '部分就绪',
  PARTIAL_SUCCESS: '部分成功',
  PENDING: '待处理',
  PLANNED: '规划中',
  POSITIVE: '正向',
  POST_CLOSE: '盘后样本',
  PROJECT_USER_DAILY: '生成用户日报投影',
  PROMOTED: '已晋级',
  PROMOTE_STRATEGY: '晋级策略',
  PROMPT_STABILITY: '提示词稳定性',
  READY: '就绪',
  READY_FOR_REVIEW: '等待人工复核',
  REALTIME: '实时',
  REASSESS: '重新评估',
  RECOMMEND: '推荐关注',
  REDUCE: '减仓',
  REJECTED: '已拒绝',
  REJECT_STRATEGY: '拒绝策略',
  REPORT_JSON: '报告结构',
  REQUEST_ACCEPTED: '请求已受理',
  RETIRED: '已退役',
  ROLLED_BACK: '已回滚',
  ROLLBACK_STRATEGY: '回滚策略',
  RULE_BASELINE: '规则基线',
  RUNNING: '执行中',
  RUN_TRAINING: '运行模型训练',
  RUN_WEEKLY: '运行周度研究',
  RISK: '风险',
  SELL: '卖出',
  SHADOW: '影子运行',
  SIDEWAYS: '震荡',
  SKIPPED: '已跳过',
  SNAPSHOT_UNIVERSE: '固化研究股票池',
  STALE: '非实时',
  STANDBY: '可回滚',
  STOP_LOSS: '止损',
  STRONG: '强势',
  STRATEGY_PROMOTION: '策略晋级',
  STRATEGY_REJECTION: '策略拒绝',
  STRATEGY_ROLLBACK: '策略回滚',
  SUCCESS: '成功',
  SUCCESS_WITH_WARNINGS: '成功但有告警',
  SUPPORT: '支持',
  TAKE_PROFIT: '分批止盈',
  TECHNICAL: '技术面',
  TRADABLE: '可交易',
  TRENDING: '趋势行情',
  UNAVAILABLE: '数据不可用',
  UNFILLED: '未成交',
  UNKNOWN: '待确认',
  UP: '看涨',
  USER_DAILY_PROJECTION: '用户日报投影',
  VALIDATED: '已验证模型',
  VERIFIED: '已验证',
  VERIFY_LABELS: '复盘成熟预测',
  WAITING_SOURCE: '等待数据源',
  WAIT_DATA_READY: '等待完整数据',
  WARNING: '告警',
  WATCH: '观察',
  WATCHLIST: '自选股',
  WEAK: '弱势',
  WEEKLY_RESEARCH: '周度策略研究',
})

const REPLACEMENTS = Object.entries(STATUS_LABELS)
  .sort(([left], [right]) => right.length - left.length)
const WARNED_STATUS_VALUES = new Set()

export function statusLabel(value, fallback = '-') {
  if (value === null || value === undefined || value === '') return fallback
  const normalized = String(value).trim().toUpperCase()
  if (STATUS_LABELS[normalized]) return STATUS_LABELS[normalized]
  if (!WARNED_STATUS_VALUES.has(normalized)) {
    WARNED_STATUS_VALUES.add(normalized)
    console.warn(`发现未配置的状态枚举：${normalized}`)
  }
  return `未识别状态（${String(value)}）`
}

export function localizeStatusText(value, fallback = '-') {
  if (value === null || value === undefined || value === '') return fallback
  let result = String(value)
  for (const [code, label] of REPLACEMENTS) {
    const pattern = new RegExp(`(^|[^A-Z0-9_])${code}(?=$|[^A-Z0-9_])`, 'g')
    result = result.replace(pattern, `$1${label}`)
  }
  return result
}

export { STATUS_LABELS }
