const STATUS_LABELS = Object.freeze({
  ABSTAIN: '暂不判断',
  ACTIVE: '已启用',
  ADD: '加仓',
  AFTER_CLOSE: '收盘后',
  AUTHORIZATION: '鉴权失败',
  AVAILABLE: '可用',
  AVOID: '建议回避',
  BALANCED: '均衡震荡',
  BEAR: '弱势',
  BEFORE_OPEN: '开盘前',
  BUILD_DAILY_INSIGHT: '汇总日报结论',
  BUILD_DECISION_PLANS: '生成日报条件计划',
  BUILD_RESEARCH_DAILY_REPORT: '生成投研日报',
  BUILD_SAMPLES: '固化研究样本',
  BULL: '强势',
  BUY: '买入',
  CANCELLED: '已取消',
  CAUTIOUS: '谨慎观察',
  CANDIDATE: '候选版本',
  CANDIDATE_CREATED: '已创建候选规则',
  CHALLENGER: '候选策略',
  CHALLENGER_SHADOW: '候选策略影子运行',
  CHAMPION: '正式策略',
  CHECK_DATA_QUALITY: '检查数据质量',
  CLOSE: '收盘样本',
  COMPLETED: '已完成',
  COMPUTE_FACTORS: '计算因子',
  CRITICAL: '严重告警',
  CURRENT: '当前版本',
  CURRENT_CLOSE: '当日收盘数据',
  DATA_NOT_READY: '样本数据未就绪',
  DATA_UNAVAILABLE: '数据不可用',
  DAILY_REPORT_MISSING: '用户日报缺失',
  DETERMINISTIC_POLICY: '规则证据裁决',
  DECISION_CONFLICT: '日报结论冲突',
  DECISION: '决策',
  DEFENSIVE: '防御模式',
  DELISTING_NAME: '名称含退市标识',
  DISABLED: '已停用',
  DOWN: '看跌',
  DRAFT: '草稿',
  EMPTY: '暂无数据',
  EMPTY_RESULT: '暂无结果',
  ENABLED: '已启用',
  EVALUATED: '已评估',
  EVIDENCE_SCOPE: '证据范围',
  EVALUATE_HISTORICAL_PREDICTIONS: '评估历史预测',
  EVALUATE_PREDICTIONS: '评估成熟预测',
  EXECUTED: '已成交',
  EXCLUDED: '已排除',
  FAILED: '执行失败',
  FAILED_FINAL: '最终失败，需处理',
  FAILED_RECOVERABLE: '失败，等待自动恢复',
  FAILED_PIPELINE: '流水线失败',
  FETCH_DATA: '抓取收盘数据',
  FETCH_SOURCE_DATA: '采集研究数据',
  FINALIZED: '已冻结',
  FRESH: '数据新鲜',
  FROZEN: '已冻结',
  FUNDAMENTAL: '基本面',
  GENERATE_PREDICTIONS: '生成预测结果',
  GENERATE_STOCK_REPORTS: '生成个股报告',
  GENERATE_REPORTS: '生成个股报告',
  GLOBAL_DAILY_RESEARCH: '全局日度研究',
  GLOBAL_HISTORICAL_BOOTSTRAP: '全局历史训练初始化',
  GLOBAL_MONTHLY_TRAINING: '全局月度模型训练',
  GLOBAL_WEEKLY_RESEARCH: '全局周度策略研究',
  HEALTHY: '健康',
  HISTORICAL_BOOTSTRAP: '历史冷启动',
  HISTORICAL_RESEARCH_READY: '汇总历史研究结果',
  HIGH: '高风险',
  HIGH_RISK: '高风险',
  HOLD: '持有',
  HOLDING_CONCLUSION_MISSING: '持仓缺少当日结论',
  HUMAN: '人工操作',
  HUMAN_CHALLENGER_REJECTED: '人工拒绝候选策略',
  HUMAN_PROMOTION_APPROVED: '人工批准规则晋级',
  HUMAN_PROMOTION_CONFIRMED: '人工确认策略晋级',
  HUMAN_PROMOTION_REJECTED: '人工拒绝规则晋级',
  HUMAN_ROLLBACK_CONFIRMED: '人工确认策略回滚',
  IDLE: '等待中',
  INACTIVE: '未启用',
  IMPORT_HISTORICAL_EVIDENCE: '导入历史研究证据',
  INSUFFICIENT_DATA: '数据积累不足',
  INTRADAY: '盘中',
  LABEL_VERIFICATION: '成熟标签验证',
  LOW: '低风险',
  LOW_SAMPLE: '样本不足',
  MARKET: '市场',
  MATURED: '标签已成熟',
  MATURE_HISTORICAL_SAMPLE_LABELS: '生成历史成熟标签',
  MATURE_SAMPLE_LABELS: '生成成熟标签',
  MEDIUM: '中风险',
  MISSING: '数据缺失',
  MISSING_HISTORICAL_UNIVERSE: '缺少历史股票池',
  MODEL: '模型推理',
  MODEL_FAILURE: '模型调用失败',
  MODEL_TRAINING: '模型训练',
  MISSING_FORMAL_SAMPLE: '缺少正式样本',
  NEGATIVE: '负向',
  NETWORK: '网络异常',
  NEUTRAL: '中性',
  NO_TRIGGER: '未触发',
  NO_ACTION: '条件触发但不执行',
  NO_TRADING_DAYS: '没有可回放交易日',
  NOT_TRADING_DAY: '非交易日',
  NON_LISTED_STATUS: '非正常上市状态',
  NON_TRADABLE: '不可交易',
  PARTIAL_READY: '部分就绪',
  PARTIAL_SUCCESS: '部分成功',
  PENDING: '待处理',
  PLANNED: '规划中',
  POSITIVE: '正向',
  PIPELINE_ATTENTION: '流水线需要关注',
  PT_SECURITY: 'PT 证券',
  POST_CLOSE: '盘后样本',
  PROJECT_USER_DAILY: '生成用户日报投影',
  PROMOTED: '已晋级',
  PROMOTE_STRATEGY: '晋级策略',
  PROMPT_STABILITY: '提示词稳定性',
  READY: '就绪',
  RECONCILED_AI_REPORT: '已对齐 AI 报告与规则证据',
  READY_FOR_REVIEW: '等待人工复核',
  REALTIME: '实时',
  RATE_LIMIT: '模型限流',
  REASSESS: '重新评估',
  RECOMMEND: '推荐关注',
  REDUCE: '减仓',
  REJECTED: '已拒绝',
  REJECT_STRATEGY: '拒绝策略',
  REPORT_JSON: '报告结构',
  REQUEST_ACCEPTED: '请求已受理',
  RETIRED: '已退役',
  RETRY_PENDING: '等待自动重试',
  ROLLED_BACK: '已回滚',
  ROLLBACK_STRATEGY: '回滚策略',
  RULE_BASELINE: '规则基线',
  RUNNING: '执行中',
  RUN_TRAINING: '运行模型训练',
  RUN_WEEKLY: '运行周度研究',
  RISK: '风险',
  SELL: '卖出',
  SHADOW: '影子运行',
  SHADOW_INSUFFICIENT_DATA: '影子观察样本不足',
  SHADOW_READY_FOR_REVIEW: '影子观察等待人工复核',
  SHADOW_REJECTED: '影子观察未通过',
  SIDEWAYS: '震荡',
  SKIPPED: '已跳过',
  SNAPSHOT_UNIVERSE: '固化研究股票池',
  STALE: '非实时',
  STALE_RUNNING: '运行租约已失效',
  ST_SECURITY: 'ST 证券',
  STANDBY: '可回滚',
  STOP_LOSS: '止损',
  STRONG: '强势',
  STRATEGY_PROMOTION: '策略晋级',
  STRATEGY_FALLBACK: '策略级样本',
  STOCK: '个股样本',
  STRATEGY_REJECTION: '策略拒绝',
  STRATEGY_ROLLBACK: '策略回滚',
  STRUCTURE: '响应结构异常',
  SOURCE_HEALTH: '数据源状态异常',
  SUCCESS: '成功',
  SUCCESS_WITH_WARNINGS: '成功但有告警',
  SUPERSEDED: '已被新版本替代',
  SUPPORT: '支持',
  TAKE_PROFIT: '分批止盈',
  TECHNICAL: '技术面',
  TIMEOUT: '请求超时',
  TRAIN_HISTORICAL_MODEL: '训练历史候选模型',
  TRADABLE: '可交易',
  TRENDING: '趋势行情',
  UNAVAILABLE: '数据不可用',
  UNFILLED: '未成交',
  UNKNOWN: '待确认',
  UNIVERSE_POLLUTION: '研究池污染',
  UP: '看涨',
  UPDATE_HISTORICAL_RESEARCH: '更新历史因子与策略研究',
  USER_DAILY_PROJECTION: '用户日报投影',
  VALIDATE_HISTORICAL_EVIDENCE: '校验历史研究证据',
  VALIDATED: '已验证模型',
  VERIFIED: '已验证',
  VERIFY_LABELS: '复盘成熟预测',
  WAITING_SOURCE: '等待数据源',
  WALK_FORWARD_INSUFFICIENT_DATA: '时序验证样本不足',
  WALK_FORWARD_PASSED: '时序验证通过',
  WALK_FORWARD_REJECTED: '时序验证未通过',
  WAIT_DATA_READY: '等待完整数据',
  WARNING: '告警',
  WATCH: '观察',
  WATCHLIST: '自选股',
  WEAK: '弱势',
  WEEKLY_RESEARCH: '周度策略研究',
})

const REPLACEMENTS = Object.entries(STATUS_LABELS)
  .sort(([left], [right]) => right.length - left.length)
const WARNED_STATUS_VALUES = new Set()

function dynamicStatusLabel(normalized) {
  const replay = normalized.match(/^REPLAY_(\d+)$/)
  if (replay) return `历史回放第 ${Number(replay[1])} 批`
  return ''
}

export function statusLabel(value, fallback = '-') {
  if (value === null || value === undefined || value === '') return fallback
  const normalized = String(value).trim().toUpperCase()
  if (STATUS_LABELS[normalized]) return STATUS_LABELS[normalized]
  const dynamic = dynamicStatusLabel(normalized)
  if (dynamic) return dynamic
  if (!WARNED_STATUS_VALUES.has(normalized)) {
    WARNED_STATUS_VALUES.add(normalized)
    console.warn(`发现未配置的状态枚举：${normalized}`)
  }
  return `未识别状态（${String(value)}）`
}

export function localizeStatusText(value, fallback = '-') {
  if (value === null || value === undefined || value === '') return fallback
  let result = String(value).replace(/\bREPLAY_(\d+)\b/gi,
    (_, sequence) => `历史回放第 ${Number(sequence)} 批`)
  for (const [code, label] of REPLACEMENTS) {
    const pattern = new RegExp(`(^|[^A-Z0-9_])${code}(?=$|[^A-Z0-9_])`, 'g')
    result = result.replace(pattern, `$1${label}`)
  }
  return result
}

export { STATUS_LABELS }
